JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_BATCHED_SUBMISSIONS=true
MAX_SUBMISSION_BATCH_SIZE=100
ALLOW_ORIGIN=*
REDIS_HOST=judge0-redis
REDIS_PASSWORD=judge0_redis_password
POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_db_password
CPU_TIME_LIMIT=3
MAX_CPU_TIME_LIMIT=6
WALL_TIME_LIMIT=8
MAX_WALL_TIME_LIMIT=12
MEMORY_LIMIT=128000
MAX_MEMORY_LIMIT=256000
ENABLE_NETWORK=false
RAILS_ENV=production
